---
all:
  children:
    control_plane:
      hosts:
        pc:
          ansible_connection: local
    raspberry:
      hosts:
        rpi5:
          ansible_host: 192.168.1.50
          ansible_user: pi
