---
- name: Reboot to apply the cgroups required by k3s
  ansible.builtin.reboot:
    msg: "Rebooting the Raspberry Pi to enable the cgroups required by k3s"
    reboot_timeout: 600
    post_reboot_delay: 10

- name: Restart the swap service
  ansible.builtin.systemd_service:
    name: dphys-swapfile
    state: restarted
    daemon_reload: true
